AdelphaTimer0.3/AdelphaTimer0.3/Controllers/DemandeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdelphaTimer0._3.Models;

namespace AdelphaTimer0._3.Controllers
{
    public class DemandeController : Controller
    {
        private adelphaTimerEntities db = new adelphaTimerEntities();

        // GET: Demande
        public ActionResult Index()
        {
            var stories = db.Stories.Include(s => s.Categories).Include(s => s.Projects).Include(s => s.Ressources).Include(s => s.Sprints);
            return View(stories.ToList());
        }

        public ActionResult _Index()
        {
            var demande = db.Stories.ToList();
            return PartialView("_Index", demande);
        }

        // GET: Demande/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stories stories = db.Stories.Find(id);
            if (stories == null)
            {
                return HttpNotFound();
            }
            return View(stories);
        }

        // GET: Demande/Create
        public ActionResult Create()
        {
            ViewBag.Id_cat_st = new SelectList(db.Categories, "Id_categ", "Desc_categ");
            ViewBag.Id_p_st = new SelectList(db.Projects, "Id_proj", "Nom_proj");
            ViewBag.Id_res_st = new SelectList(db.Ressources, "Id_res", "Nom_res");
            ViewBag.Id_sp_st = new SelectList(db.Sprints, "Id_sprint", "Etat_sprint");
            return View();
        }

        // POST: Demande/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_st,Nom_st,Id_res_st,Importance_st,Estim_init_st,Demontrer_st,Note,Id_cat_st,Demande_par_st,Demande_le_st,Id_p_st,Id_sp_st,Actif_st")] Stories stories)
        {
            if (ModelState.IsValid)
            {
                db.Stories.Add(stories);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Id_cat_st = new SelectList(db.Categories, "Id_categ", "Desc_categ", stories.Id_cat_st);
            ViewBag.Id_p_st = new SelectList(db.Projects, "Id_proj", "Nom_proj", stories.Id_p_st);
            ViewBag.Id_res_st = new SelectList(db.Ressources, "Id_res", "Nom_res", stories.Id_res_st);
            ViewBag.Id_sp_st = new SelectList(db.Sprints, "Id_sprint", "Etat_sprint", stories.Id_sp_st);
            return View(stories);
        }

        // GET: Demande/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stories stories = db.Stories.Find(id);
            if (stories == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_cat_st = new SelectList(db.Categories, "Id_categ", "Desc_categ", stories.Id_cat_st);
            ViewBag.Id_p_st = new SelectList(db.Projects, "Id_proj", "Nom_proj", stories.Id_p_st);
            ViewBag.Id_res_st = new SelectList(db.Ressources, "Id_res", "Nom_res", stories.Id_res_st);
            ViewBag.Id_sp_st = new SelectList(db.Sprints, "Id_sprint", "Etat_sprint", stories.Id_sp_st);
            return View(stories);
        }

        // POST: Demande/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_st,Nom_st,Id_res_st,Importance_st,Estim_init_st,Demontrer_st,Note,Id_cat_st,Demande_par_st,Demande_le_st,Id_p_st,Id_sp_st,Actif_st")] Stories stories)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stories).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id_cat_st = new SelectList(db.Categories, "Id_categ", "Desc_categ", stories.Id_cat_st);
            ViewBag.Id_p_st = new SelectList(db.Projects, "Id_proj", "Nom_proj", stories.Id_p_st);
            ViewBag.Id_res_st = new SelectList(db.Ressources, "Id_res", "Nom_res", stories.Id_res_st);
            ViewBag.Id_sp_st = new SelectList(db.Sprints, "Id_sprint", "Etat_sprint", stories.Id_sp_st);
            return View(stories);
        }

        // GET: Demande/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stories stories = db.Stories.Find(id);
            if (stories == null)
            {
                return HttpNotFound();
            }
            return View(stories);
        }

        // POST: Demande/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Stories stories = db.Stories.Find(id);
            db.Stories.Remove(stories);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdelphaTimer0.3/AdelphaTimer0.3/Controllers/HomeController.cs
using AdelphaTimer0._3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdelphaTimer0._3.Controllers
{
    public class HomeController : Controller
    {
        public adelphaTimerEntities bdd = new adelphaTimerEntities();
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        
    }
}

AdelphaTimer0.3/AdelphaTimer0.3/Controllers/TachesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdelphaTimer0._3.Models;

namespace AdelphaTimer0._3.Controllers
{
    public class TachesController : Controller
    {
        private adelphaTimerEntities db = new adelphaTimerEntities();

        // GET: Taches
        public ActionResult Index()
        {
            var tasks = db.Tasks.Include(t => t.Ressources).Include(t => t.Sponsor).Include(t => t.Stories);
            return View(tasks.ToList());
        }

        [ChildActionOnly]
        public ActionResult _Index()
        {
            var tasks = db.Tasks.ToList();
            return PartialView("_Index", tasks);
        }

        [ChildActionOnly]
        public ActionResult _DayTach()
        {
            var daytach = db.Tasks.ToList();
            return PartialView("_DayTach", daytach);
        }

        [ChildActionOnly]
        public ActionResult _Daywork()
        {
            var daywork = db.Tasks.ToList();
            return PartialView("_Daywork", daywork);
        }

        // GET: Taches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tasks tasks = db.Tasks.Find(id);
            if (tasks == null)
            {
                return HttpNotFound();
            }
            return View(tasks);
        }

        // GET: Taches/Create
        public ActionResult Create()
        {
            ViewBag.Id_res_task = new SelectList(db.Ressources, "Id_res", "Nom_res");
            ViewBag.Id_spon_task = new SelectList(db.Sponsor, "Id_spon", "Desc_spon");
            ViewBag.Id_st_task = new SelectList(db.Stories, "Id_st", "Nom_st");
            return View();
        }

        // POST: Taches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_task,Id_st_task,Nom_task,Desc_task,Id_res_task,D_D_est_task,D_F_est_task,Travail_est_task,D_D_task,D_F_task,Travail_task,Id_spon_task,Valide_le_task,Actif_task")] Tasks tasks)
        {
            if (ModelState.IsValid)
            {
                db.Tasks.Add(tasks);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Id_res_task = new SelectList(db.Ressources, "Id_res", "Nom_res", tasks.Id_res_task);
            ViewBag.Id_spon_task = new SelectList(db.Sponsor, "Id_spon", "Desc_spon", tasks.Id_spon_task);
            ViewBag.Id_st_task = new SelectList(db.Stories, "Id_st", "Nom_st", tasks.Id_st_task);
            return View(tasks);
        }

        // GET: Taches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tasks tasks = db.Tasks.Find(id);
            if (tasks == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_res_task = new SelectList(db.Ressources, "Id_res", "Nom_res", tasks.Id_res_task);
            ViewBag.Id_spon_task = new SelectList(db.Sponsor, "Id_spon", "Desc_spon", tasks.Id_spon_task);
            ViewBag.Id_st_task = new SelectList(db.Stories, "Id_st", "Nom_st", tasks.Id_st_task);
            return View(tasks);
        }

        // POST: Taches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_task,Id_st_task,Nom_task,Desc_task,Id_res_task,D_D_est_task,D_F_est_task,Travail_est_task,D_D_task,D_F_task,Travail_task,Id_spon_task,Valide_le_task,Actif_task")] Tasks tasks)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tasks).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id_res_task = new SelectList(db.Ressources, "Id_res", "Nom_res", tasks.Id_res_task);
            ViewBag.Id_spon_task = new SelectList(db.Sponsor, "Id_spon", "Desc_spon", tasks.Id_spon_task);
            ViewBag.Id_st_task = new SelectList(db.Stories, "Id_st", "Nom_st", tasks.Id_st_task);
            return View(tasks);
        }

        // GET: Taches/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tasks tasks = db.Tasks.Find(id);
            if (tasks == null)
            {
                return HttpNotFound();
            }
            return View(tasks);
        }

        // POST: Taches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tasks tasks = db.Tasks.Find(id);
            db.Tasks.Remove(tasks);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdelphaTimer0.3/AdelphaTimer0.3/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdelphaTimer0._3.Models;

namespace AdelphaTimer0._3.Controllers
{
    public class TeamsController : Controller
    {
        private adelphaTimerEntities db = new adelphaTimerEntities();

        // GET: Teams
        public ActionResult Index()
        {
            return View(db.Teams.ToList());
        }

        [ChildActionOnly]
        public ActionResult _Index()
        {
            var tames = db.Teams.ToList();
            return PartialView("_Index", tames);
        }

        // GET: Teams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teams teams = db.Teams.Find(id);
            if (teams == null)
            {
                return HttpNotFound();
            }
            return View(teams);
        }

        // GET: Teams/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Teams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_team,Nom_team,Actif_team")] Teams teams)
        {
            if (ModelState.IsValid)
            {
                db.Teams.Add(teams);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(teams);
        }

        // GET: Teams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teams teams = db.Teams.Find(id);
            if (teams == null)
            {
                return HttpNotFound();
            }
            return View(teams);
        }

        // POST: Teams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_team,Nom_team,Actif_team")] Teams teams)
        {
            if (ModelState.IsValid)
            {
                db.Entry(teams).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(teams);
        }

        // GET: Teams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teams teams = db.Teams.Find(id);
            if (teams == null)
            {
                return HttpNotFound();
            }
            return View(teams);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Teams teams = db.Teams.Find(id);
            db.Teams.Remove(teams);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdelphaTimer0.3/AdelphaTimer0.3/Views/Home/Index.cshtml
<head>
    <style type="text/css">
       
       

header,
footer,
nav,
section {
    display: block;
   
}

/* Styles for basic forms
-----------------------------------------------------------*/

fieldset 
{
    border:1px solid #ddd;
    padding:0 1.4em 1.4em 1.4em;
    margin:0 0 1.5em 0;
}

legend 
{
    font-size:1.2em;
    font-weight: bold;
}

textarea 
{
    min-height: 75px;
}

.editor-label 
{
    margin: 1em 0 0 0;
}

.editor-field 
{
    margin:0.5em 0 0 0;
}


/* Styles for validation helpers
-----------------------------------------------------------*/
.field-validation-error
{
    color: #ff0000;
}

.field-validation-valid
{
    display: none;
}

.input-validation-error
{
    border: 1px solid #ff0000;
    background-color: #ffeeee;
}

.validation-summary-errors
{
    font-weight: bold;
    color: #ff0000;
}

.validation-summary-valid
{
    display: none;
}


.pageHeader {height:20px; background-color:#056cd5; padding:10px 10px; margin-bottom:10px; color:White; position:relative;}
.pageHeader h1{font:normal 1.2em Arial; color:White; margin:0px; padding:0px;}
.pageHeader .platformular {position:absolute; top:10px; right:10px;}
.pageBody {margin:0 10px;}
.pageFooter {clear:both; padding-top:10px; width:100%; text-align:center; font-size:0.8em; color:#686868; margin:25px 0 0 0; border-top:solid 1px #e7e7e7;}
        
        
        
        
         .dashboard {
            float: left;
            width: 100%;
            
        }

            .dashboard .dashboard3col {
                width: 100%;
                float: left;
            }

        .dashboardCol {
            float: left;
            width: 33%;
            overflow: hidden;
            margin: 0;
        }

        .dashboardItem {
            margin: 0 10px 10px 0;
            border: solid 1px #e7e7e7;
        }

        .dashboardItemHeader {
            font-size: 1.2em;
            font-weight: bold;
            padding: 10px 15px;
            background-color: rgba(71, 165, 243, 0.23);
        }

        .dashboardItemBody {
            margin: 10px;
            overflow: hidden;
        }

        .dashboardFooter {
            clear: both;
            width: 100%;
            background-color: Red;
        }

        .tbl {
            table-layout: auto;
            border-collapse: collapse;
            width: 100%;
        }

            .tbl thead th {
                border-bottom: solid 1px #ededed;
                background-color: #ededed;
                padding: 5px;
                text-align: left;
                color: #9c9c9c;
                font-size: 0.9em;
                font-weight: normal;
            }

            .tbl tbody td {
                border-bottom: solid 1px #ededed;
                padding: 5px;
                color: #686868;
                font-size: 0.9em;
            }
    </style>

</head>

<body>
   
    <div class="pageBody">
        <div class="dashboard">
            <div class="dashboard3Col">
                <div class="dashboardCol">
                    @{Html.RenderAction("_Index", "Projects");}
                    @{Html.RenderAction("_Index", "Demande");}  
                    @{Html.RenderAction("_Index", "Taches");}                 
                  
                </div>
                <div class="dashboardCol">
                    @{Html.RenderAction("_DayTach", "Taches");}              
                    @{Html.RenderAction("_Index", "Sprints");}
                    @{Html.RenderAction("_Daywork", "Taches");}
                </div>
                <div class="dashboardCol">
                    @{Html.RenderAction("_Index", "Teams");}
                    @{Html.RenderAction("_Index", "Ressources");}  
                    @{Html.RenderAction("_Index", "Taches");}                  
                </div>               
                <div class="dashboardFooter"></div>
            </div>
        </div>
    </div>
    <div class="pageFooter">
        AdelphaTimer
    </div>
</body>